config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }

  # devise_scope :user do
  #   get "sign_in", to: "users/sessions#new"
  #   get "sign_out", to: "users/sessions#destroy" 
  # end

  resources :users, :only => [:show, :edit] do
    resources :cards, only: [:new, :create, :index]
    resources :addresses, only: [:new, :create, :show, :edit, :update]

    member do
      get 'mypage_identification'
      get 'telephone_authentication'
    end
    
    collection do
      get 'signup_complete'
      get 'signup'
      get 'logout'
    end
  end


  resources :items do
    resources :likes, only: [:create, :destroy]

    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
      get 'show_all'
      get 'show_user_all'
      get 'show_other_all'
      get 'search'
      get 'search_ransack'
    end

    member do
      get 'purchase_confirmation'
      get 'payment_complete'
      patch 'switch_status'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_item

  def create
    @like = current_user.likes.create(user_id: current_user.id, item_id: params[:item_id])
    @likes = Like.where(item_id: params[:item_id])
    @item.reload
  
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    @like.destroy
    @likes = Like.where(item_id: params[:item_id])
    @item.reload
    # redirect_back(fallback_location: root_path)
  end
  

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/views/likes/_like.html.haml
- if user_signed_in?
  - if current_user.already_liked?(@item)
    %button.item_buttons__left--like
      = link_to item_like_path(item_id: @item.id,id: @item.likes[0].id), method: :delete, remote: true do
        = fa_icon 'heart', class: 'icon-heart', id: "likes_buttons_#{@item.id}"
        %span いいね!
        %span.fade-in-down
          = @item.likes.count
  - else
    %button.item_buttons__left--like
      = link_to item_likes_path(@item.id), method: :post, remote: true do
        = fa_icon 'heart-o', class: 'icon-heart-o', id: "likes_buttons_#{@item.id}"
        %span いいね!
        %span.fade-in-down
          = @item.likes.count
- else 
  %button.item_buttons__left--like
    = fa_icon 'heart-o', class: 'icon-heart-o'
    %span いいね!
    %span.fade-in-down
      = @item.likes.count

app/views/likes/create.js.erb
$('#likes_buttons_<%= @item.id %>').html("<%= j(render partial: 'likes/like', locals: {item: @item}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @item.id %>').html("<%= j(render partial: 'likes/like', locals: {item: @item}) %>");