config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }

  # devise_scope :user do
  #   get "sign_in", to: "users/sessions#new"
  #   get "sign_out", to: "users/sessions#destroy" 
  # end

  resources :users, :only => [:show, :edit] do
    resources :cards, only: [:new, :create, :index]
    resources :addresses, only: [:new, :create, :show, :edit, :update]

    member do
      get 'mypage_identification'
      get 'telephone_authentication'
    end
    
    collection do
      get 'signup_complete'
      get 'signup'
      get 'logout'
    end
  end


  resources :items do
    resources :likes, only: [:create, :destroy]

    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
      get 'show_all'
      get 'show_user_all'
      get 'show_other_all'
      get 'search'
      get 'search_ransack'
    end

    member do
      get 'purchase_confirmation'
      get 'payment_complete'
      patch 'switch_status'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :sns_credentials, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,

         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  has_one :address
  has_many :items
  has_many :buyer_tradings, class_name: 'Trading'


  reg_mail_address = /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\z/
  reg_alphanumeric_6characters = /\A[a-zA-Z0-9]{6,}+\z/
  # reg_prefecture_choce = /\A(?!.*--未選択--).*\z/
  reg_only_kana = /\A[ァ-ヴ]+\z/
  # reg_zip_code = /\A[0-9]{3}\-[0-9]{4}+\z/
  # reg_intger_10or11_characters = /\A[0-9]{10,11}+\z/
  # reg_intger_14or16_characters = /\A[0-9]{14,16}+\z/
  # reg_intger_3or4_characters = /\A[0-9]{3,4}+\z/
  reg_date_year = /\A\d{4}-\d{2}-\d{2}\z/

  validates :nickname,
    presence: true
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: reg_mail_address }
  validates :password,
    presence: true,
    confirmation: true,
    format: { with: reg_alphanumeric_6characters }
  validates :first_name,
    presence: true
  validates :last_name,
    presence: true
  validates :first_kana,
    presence: true,
    format: { with: reg_only_kana }
  validates :last_kana,
    presence: true,
    format: { with: reg_only_kana }
  validates :birthday,
    presence: true,
    format: { with: reg_date_year }
   


   def already_liked?(item)
     self.likes.exists?(item_id: item.id)
   end

   def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

   def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email
      )
    end
    return {user: user}
   end

   def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    end
    return { user: user ,sns: sns}
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end
  

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    telephone_authentication_user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    telephone_authentication_user_path(current_user.id)
  end

  def create
    if params[:user][:password].blank?
      @user = User.create(user_via_sns_params)
      sns = SnsCredential.create(user_id: @user.id,uid: params[:user][:uid], provider: params[:user][:provider])
      sign_in_and_redirect @user, event: :authentication
    else 
      super
    end
  end

  private
  def user_via_sns_params
    password = Devise.friendly_token.first(6)
    params.require(:user).permit(:nickname, :email, :first_name, :last_name, :first_kana, :last_kana, :birthday).merge(password: password, password_confirmation: password)
  end

  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # サインイン後のリダイレクト先をマイページへ
  # def after_sign_in_path_for(resource)
  #   # flash[:notice] = "ログインに成功しました" #　 <-任意で
  #   user_path(current_user.id)  #　指定したいパスに変更
  # end

  # サインアウト後のリダイレクト先をトップページへ
  def after_sign_out_path_for(resource)
      # flash[:alert] = "ログアウトしました"
      root_path
  end

  private

  def check_captcha
    self.resource = resource_class.new sign_in_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:signup]

  def show
    @items = current_user.items
  end

  def edit
  end

  def mypage_identification
  end


  def signup
  end

  def signup_complete
  end

  def telephone_authentication
  end

  def logout
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_left-content.html.haml
.left-content
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item active', data:{turbolinks: :false} do
          マイページ
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          お知らせ
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          やることリスト
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          いいね！一覧
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to new_item_path, class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          出品する
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to show_user_all_items_path, class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          出品した商品 - 出品中
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          出品した商品 - 取引中
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          出品した商品 - 売却済み
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          購入した商品 - 取引中
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          購入した商品 - 過去の取引
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          ニュース一覧
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          評価一覧
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          ガイド
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          お問い合わせ
          = fa_icon 'angle-right', class: 'icon-angle-right'

    %h3.mypage-nav__head メルペイ
    %ul.mypage-nav__list
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          売上・振込申請
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          ポイント
          = fa_icon 'angle-right', class: 'icon-angle-right'
  
    %h3.mypage-nav__head 設定
    %ul.mypage-nav__list
      %li
        = link_to edit_user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          プロフィール
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        - if current_user.address.present?
          = link_to edit_user_address_path(current_user.id, current_user.address.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
            発送元・お届け先住所の変更
            = fa_icon 'angle-right', class: 'icon-angle-right'
        - else
          = link_to new_user_address_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
            発送元・お届け先住所の登録
            = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to  user_cards_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          支払い方法
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          メール/パスワード
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to mypage_identification_user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          本人情報
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to user_path(current_user.id), class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          電話番号の確認
          = fa_icon 'angle-right', class: 'icon-angle-right'
      %li
        = link_to logout_users_path, class: 'mypage-nav__list__item', data:{turbolinks: :false} do
          ログアウト
          = fa_icon 'angle-right', class: 'icon-angle-right'

app/views/users/destroy.html.haml
.default-container
  
  =render partial: 'items/header'

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .logout-container
      .logout-container__main
        %form.logout-container__main__inner{action: "https://www.mercari.com/jp/logout/", method: "POST", novalidate: "novalidate"}
          .logout-container__main__inner__button
            %button.logout-container__main__inner__button--red{type: "submit"} ログアウト
            %input{name: "__csrf_value", type: "hidden", value: "d50f29037e7e2eb8dcd90e46572e88e7de28f5cf82bf07e93305c96e0d5ace1685dacd3057d185636ceb973fb72db7a9a3cee5adbde993b15e3eb6ace3279cf09"}/

  =render partial: 'items/footer'

app/views/users/edit.html.haml
.default-container

  =render partial: 'items/header'

  .breadcrumb
    - breadcrumb :user_edit
    = breadcrumbs separator: " &rsaquo; "

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .user-edit_right-content
      %section.user-edit_info
        %h2.user-edit_info__head プロフィール
        = form_for "" do |f|
          .user-edit_profile-head
            %figure.user-edit_profile-head__photo
              = image_tag "member_nophoto.jpg",size: '60x60', alt: ""
            = f.text_field :text, class: "user-edit_profile-head__form", placeholder: "例)AYA☆セール中", value: "にゃん太"
          .user-edit_profile-content
            = f.text_area :text2, class: "user-edit_profile-content__form", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", value: "ほげほげ"
            = f.submit "変更する", class: "user-edit_profile-content__btn"

  =render partial: 'items/footer'

app/views/users/logout.html.haml
.default-container
  
  =render partial: 'items/header'

  .breadcrumb
    - breadcrumb :user_logout
    = breadcrumbs separator: " &rsaquo; "

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .logout-container
      .logout-container__main
        = link_to "ログアウト", destroy_user_session_path, method: :delete

  =render partial: 'items/footer'

app/views/users/mypage-identification.html.haml
.default-container
  
  =render partial: 'items/header'

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .user-mypage_identification_right-content
      

  =render partial: 'items/footer'

app/views/users/mypage_identification.html.haml
.default-container
  
  =render partial: 'items/header'

  .breadcrumb
    - breadcrumb :user_mypage_identification
    = breadcrumbs separator: " &rsaquo; "

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .user_mypage_identification_right-content
      %h2.mi_head 本人情報の登録

      .mi_group
        %p お客さまの本人情報をご登録ください。
        %p 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.text-right
          = link_to root_path, class: 'mi_group__link', target: "_blank", data:{turbolinks: :false} do
            本人確認書類のアップロードについて
            = fa_icon 'angle-right', class: 'icon-angle-right bold'

      .mi_group
        %p.bold お名前
        %p 石ノ森 章太郎

      .mi_group
        %p.bold お名前カナ
        %p イシノモリ ショウタロウ

      .mi_group
        %p.bold{for: "birthday"} 生年月日
        %p 1938/01/25

      = form_with url: 'users_path', local: true, class: 'mi_form' do |f|

        .mi_form__group
          %label.bold{ for: "postalcode" } 郵便番号
          %label.mi_form__group--arbitrary 任意
          = f.text_field :postalcode, name: "postalcode", class: 'mi_form__group__input', placeholder: "例）123-4567"

        .mi_form__group
          %label.bold{ for: "prefecture" } 都道府県
          %label.mi_form__group--arbitrary 任意
          .mi_form__group--select-wrap
            = fa_icon 'angle-down 2x', class: 'icon-angle-down bold'
            = f.select :prefecture, Address.prefectures.keys

        .mi_form__group
          %label.bold{ for: "city" } 市区町村
          %label.mi_form__group--arbitrary 任意
          = f.text_field :city, name: "city", class: 'mi_form__group__input', placeholder: "例）石巻市"

        .mi_form__group
          %label.bold{ for: "number" } 番地
          %label.mi_form__group--arbitrary 任意
          = f.text_field :number, name: "number", class: 'mi_form__group__input', placeholder: "例）中瀬２−７"
          
        .mi_form__group
          %label.bold{ for: "building" } 建物名
          %label.mi_form__group--arbitrary 任意
          = f.text_field :building, name: "building", class: 'mi_form__group__input', placeholder: "例）石ノ森萬画館"

        = f.submit '登録する',class: 'mi_form__submit_btn'

      .mi_group
        %p.text-right
          = link_to root_path, class: 'mi_group__link', target: "_blank", data:{turbolinks: :false} do
            本人情報の登録について
            = fa_icon 'angle-right', class: 'icon-angle-right bold'

  =render partial: 'items/footer'

app/views/users/signup.html.haml
.default-container

  = render 'devise/shared/only_logo_header'

  .signup
    %h2
      新規会員登録
    .choose-registration-way
      %ul
        %li.email-address
          = link_to new_user_registration_path do
            = fa_icon "envelope"
            メールアドレスで登録する
        %li.facebook
          = link_to user_facebook_omniauth_authorize_path do
            = fa_icon "facebook-square"
            Facebookで登録する
        %li.google
          = link_to user_google_oauth2_omniauth_authorize_path do
            = fa_icon "google"
            Googleで登録する

  = render 'devise/shared/gray_footer'

app/views/users/signup_complete.html.haml
.default-container

  .header_signup_complete
    %h1.header_signup_complete--wrap
      = link_to root_path, class: 'header_only-logo--wrap__link', data:{turbolinks: :false} do
        = image_tag "mercari_logo.png", class: 'header_only-logo--wrap__link__image', size: '185x52', alt: "mercari"
    .header_signup_complete__stage
      %ol.header_signup_complete__stage__list.clearfix
        %li
          %span 会員情報
          .stage-status.active 
        %li
          %span 電話番号認証
          .stage-status.active 
        %li
          %span お届け先住所入力
          .stage-status.active 
        %li
          %span 支払い方法
          .stage-status.active 
        %li.active 
          %span 完了
          .stage-status.active 

  %main.signup_complete_container
    %h2.signup_complete_head 会員登録完了

    .signup_complete_group
      .signup_complete_group__item
        %p ありがとうございます。
        %p 会員登録が完了しました。
        
      .signup_complete_group__item
        = link_to 'メルカリを始める', root_path, class: 'signup_complete_group__item__link', data:{turbolinks: :false}

  =render partial: 'devise/shared/gray_footer'

app/views/users/telephone_authentication.html.haml
.default-container
  
  .header_telephone_authentication
    %h1.header_telephone_authentication--wrap
      = link_to root_path, class: 'header_telephone_authentication--wrap__link', data:{turbolinks: :false} do
        = image_tag "mercari_logo.png", class: 'header_telephone_authentication--wrap__link__image', size: '185x52', alt: "mercari"
    .header_telephone_authentication__stage
      %ol.header_telephone_authentication__stage__list.clearfix
        %li
          %span 会員情報
          .stage-status.active 
        %li.active 
          %span 電話番号認証
          .stage-status.active 
        %li
          %span お届け先住所入力
          .stage-status
        %li
          %span 支払い方法
          .stage-status
        %li
          %span 完了
          .stage-status

  .telephone_authentication_right-content
    %h2.mi_head 電話番号の確認

    = form_with url: '', local: true, class: 'mi_form' do |f|

      .mi_form__group
        %label.bold{ for: "phone_number" } 携帯電話の番号
        = f.text_field :phone_number, name: "phone_number", class: 'mi_form__group__input', placeholder: "例）09012345678"
        %p 本人確認のため、携帯電話のSMS（ショートメッセージサービス）を利用して認証を行います。

      /= f.submit '登録する',class: 'mi_form__submit_btn'
      = link_to '次へ進む', new_user_address_path(current_user.id), class: 'mi_form__submit_btn', data:{turbolinks: :false}
      %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

    .text-right
      = link_to root_path, target: "_blank", data:{turbolinks: :false} do
        電話番号の確認が必要な理由
        = fa_icon 'angle-right', class: 'icon-angle-right bold'

  =render partial: 'devise/shared/gray_footer'