config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }

  # devise_scope :user do
  #   get "sign_in", to: "users/sessions#new"
  #   get "sign_out", to: "users/sessions#destroy" 
  # end

  resources :users, :only => [:show, :edit] do
    resources :cards, only: [:new, :create, :index]
    resources :addresses, only: [:new, :create, :show, :edit, :update]

    member do
      get 'mypage_identification'
      get 'telephone_authentication'
    end
    
    collection do
      get 'signup_complete'
      get 'signup'
      get 'logout'
    end
  end


  resources :items do
    resources :likes, only: [:create, :destroy]

    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
      get 'show_all'
      get 'show_user_all'
      get 'show_other_all'
      get 'search'
      get 'search_ransack'
    end

    member do
      get 'purchase_confirmation'
      get 'payment_complete'
      patch 'switch_status'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :trading
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  # belongs_to :category
  
  # reg_price_range = /[3-9]\d{2}|[1-9]\d{3,6}/

  validates :image,
    presence: true
  validates :name,
    presence: true,
    length: { maximum: 40 }
  validates :description,
    presence: true,
    length: { maximum: 1000 }
  validates :item_status,
    presence: true
  validates :payment,
    presence: true
  validates :delivery_type,
    presence: true
  validates :delivery_region,
    presence: true
  validates :delivery_days,
    presence: true
  validates :price,
    presence: true

    # TO DO 価格の数値範囲のバリデーション一旦保留
    # format: { with: reg_price_range }

  mount_uploader :image, ImageUploader

  enum item_status: {"---": 0, 新品、未使用: 1, 未使用に近い: 2, 目立った傷や汚れなし: 3, やや傷や汚れあり: 4, 傷や汚れあり: 5, 全体的に状態が悪い: 6}, _prefix: true
  enum delivery_type: {"---": 0, "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2}, _prefix: true
  enum payment: {"---": 0, "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2}, _prefix: true
  enum delivery_days: {"---": 0, "1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3}, _prefix: true
  enum delivery_region: {"---": 0, 北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7, 東京都: 8, 神奈川県: 9, 埼玉県: 10, 千葉県: 11, 茨城県: 12, 栃木県: 13, 群馬県: 14, 山梨県: 15, 新潟県: 16, 長野県: 17, 富山県: 18, 石川県: 19, 福井県: 20, 愛知県: 21, 岐阜県: 22, 静岡県: 23, 三重県: 24, 大阪府: 25, 兵庫県: 26, 京都府: 27, 滋賀県: 28, 奈良県: 29, 和歌山県: 30, 鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39, 福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47}, _prefix: true

  def self.public_item_status
    item_statues.without("---")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :show_all, :search, :search_ransack]
  before_action :set_item, only: [:edit, :update, :destroy, :switch_status, :purchase_confirmation, :pay, :payment_complete]
  before_action :check_user, only: [:edit, :switch_status]
  before_action :check_trading_status, only: [:edit, :switch_status]
  before_action :check_purchase_confirmation, only: [:purchase_confirmation, :pay]
  before_action :fuzzy_search, only: [:index, :search]

  def index
    @parents = Category.all.order("id ASC").limit(2)
    @items = Item.order("created_at DESC")
    @items_limit_4 = @items.left_joins(:trading).where(tradings: {status: "出品中"}).limit(4)
    if user_signed_in?
      @items_user = current_user.items.limit(4).order("created_at DESC")
      @items_other = @items.left_joins(:trading).where(tradings: {status: "出品中"}).where.not(user_id: current_user.id).limit(4)
    end
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
  
    good_trades = Trading.where(item_id: @user.items.ids, rating: 0)
    @number_of_goods = good_trades.count
    normal_trades = Trading.where(item_id: @user.items.ids, rating: 1)
    @number_of_normals = normal_trades.count
    bad_trades = Trading.where(item_id: @user.items.ids, rating: 2)
    @number_of_bads = bad_trades.count

    
    @like = Like.new
   

  end
  
  def new
    @item = Item.new
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
       @category_parent_array << parent.name
    end
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(
      image: item_params[:image],
      name: item_params[:name],
      description: item_params[:description],
      item_status: item_params[:item_status],
      delivery_type: item_params[:delivery_type],
      payment: 1,
      delivery_region: item_params[:delivery_region],
      delivery_days: item_params[:delivery_days],
      price: item_params[:price],
      user_id: current_user.id
    )

    if @item.save
      @trading = Trading.create(
        item_id: @item.id,
        status: 0,
        rating: "",
        buyer_id: current_user.id
      )
      redirect_to :root and return
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.user_id == current_user.id
      @item.update(
        image: item_params[:image] ? item_params[:image] : @item.image,
        name: item_params[:name],
        description: item_params[:description],
        item_status: item_params[:item_status],
        payment: @item.payment,
        delivery_type: item_params[:delivery_type],
        delivery_region: item_params[:delivery_region],
        delivery_days: item_params[:delivery_days],
        price: item_params[:price]
      )
      redirect_to item_path(@item.id)
    else
      redirect_to item_path(@item.id)
    end
  end

  def destroy
    @item.destroy if @item.user_id == current_user.id
    redirect_to root_path
  end

  def show_all
    @items = Item.left_joins(:trading).where(tradings: {status: "出品中"}).order("created_at DESC").limit(40)
  end

  def show_user_all
    @items = current_user.items.limit(20).order("created_at DESC")
  end

  def show_other_all
    @items = Item.left_joins(:trading).where(tradings: {status: "出品中"}).where.not(user_id: current_user.id).limit(20).order("created_at DESC")
  end

  def purchase_confirmation
    @address = current_user.address
  end

  def payment_complete
  end

  def pay
    @trading = @item.trading
    if @trading.status == "出品中"
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      Payjp::Charge.create(
      amount: params[:amount],
      card:params['payjp-token'],
      currency: 'jpy'
      )
      @trading.update(
        item_id: @trading.item_id,
        status: 2,
        rating: "",
        buyer_id: @trading.buyer_id
      )
      redirect_to payment_complete_item_path
    else
      redirect_to item_path(@item.id)
    end
  end

  def switch_status
    @trading = @item.trading
    if @trading.status == "出品中"
      @trading.update(
        item_id: @trading.item_id,
        status: 3,
        rating: "",
        buyer_id: @trading.buyer_id
      )
      redirect_to item_path(@item.id)
    elsif @trading.status == "出品停止中"
      @trading.update(
        item_id: @trading.item_id,
        status: 0,
        rating: "",
        buyer_id: @trading.buyer_id
      )
      redirect_to item_path(@item.id)
    else
      redirect_to item_path(@item.id)
    end
  end

  def search
    @typed_keyword = params[:keyword]
    @amount = @search.length
  end

  def search_ransack
    @q = Item.ransack(params[:q])
    @trading = Trading.all
    @items = @q.result.includes(:trading)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :item_status, :payment, :delivery_type, :delivery_region, :delivery_days, :price, :category).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def check_user
    redirect_to root_path unless @item.user_id == current_user.id
  end

  def check_trading_status
    redirect_to show_user_all_items_path(current_user.id) unless @item.trading.status == "出品中" || @item.trading.status == "出品停止中"
  end

  def check_purchase_confirmation
    redirect_to root_path if current_user.id == @item.user_id
    @trading = @item.trading
    redirect_to root_path unless @trading.status == "出品中"
  end

  def fuzzy_search
    @search = Item.where('name LIKE(?)', "%#{params[:keyword]}%").order("created_at DESC").limit(132)
  end

  def search_params
    params[:q] || {
      name_or_description_cont: params[:q][:name_or_description_cont],
      item_status: params[:q][:item_status],
      trading_status_eq: params[:q][:trading_status_eq]
    }
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "¥ #{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/items/_categories.html.haml
.genre-box
  %ul.pc-header-nav__parent-wrap{data: {mega: 1}}
    - @parents.each do |parent|
      %li.pc-header-nav__parent
        = parent.name
  
        .sub-box
          %ul.pc-header-nav__child-wrap{data: {mega: 2}}
            - parent.children.each do |child|
              %li.pc-header-nav__child
                = child.name
                 
                .detail-box
                  %ul.pc-header-nav__grand-child-wrap{data: {mega: 3}}
                    - child.children.each do |grandchild|
                      %li.pc-header-nav__grand-child
                        = grandchild.name

app/views/items/_footer.html.haml
%footer.all-page-footer
  %nav.clearfix
    .footer-part
      %h2.footer-part__head メルカリについて
      %ul
        %li
          = link_to root_path do
            会社概要（運営会社）
        %li
          = link_to root_path do
            採用情報
        %li
          = link_to root_path do
            プレスリリース
        %li
          = link_to root_path, target: "_blank" do
            公式ブログ
        %li
          = link_to root_path do
            メルカリロゴ利用ガイドライン
        %li.footer-part__head--footer-social-link
          = link_to root_path, target: "_blank" do
            = fa_icon 'twitter'
        %li.footer-part__head--footer-social-link
          = link_to root_path, target: "_blank" do
            = fa_icon 'facebook-square'
    .footer-part
      %h2.footer-part__head ヘルプ＆ガイド
      %ul
        %li
          = link_to root_path do
            メルカリガイド
        %li
          = link_to root_path do
            らくらくメルカリ便
        %li
          = link_to root_path do
            ゆうゆうメルカリ便
        %li
          = link_to root_path do
            大型メルカリ便
        %li
          = link_to root_path do
            車体取引ガイド
        %li
          = link_to root_path, target: "_blank" do
            メルカリあんしん・あんぜん宣言！
        %li
          = link_to root_path do
            偽ブランド品撲滅への取り組み
        %li
          = link_to root_path do
            メルカリボックス
    .footer-part.full-width
      %h2.footer-part__head プライバシーと利用規約
      .footer-part__inner-footer-part
        .footer-part__inner-footer-part--left
          %ul
            %li
              = link_to root_path do
                プライバシーポリシー
            %li
              = link_to root_path do
                メルカリ利用規約
            %li
              = link_to root_path do
                あんしんスマホサポート制度に関する利用特約
            %li
              = link_to root_path do
                コンプライアンスポリシー
        .footer-part__inner-footer-part--right
          %ul
            %li
              = link_to root_path do
                個人データの安全管理に係る基本方針
            %li
              = link_to root_path do
                特定商取引に関する表記
            %li
              = link_to root_path do
                資金決済法に基づく表示
            %li
              = link_to root_path do
                法令順守と犯罪抑止のために
    .footer-part.footer-nav-lang
      %h2.footer-part__head 国
      %ul
        %li
          = link_to root_path, class: "active" do
            日本   
        %li
          = link_to root_path do
            United States
  .footer-lower
    = link_to root_path, class: "footer-logo" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?891577966", size:"124×33", alt: "mercari"
    %span.footer-copyright
      %small © 2019 Mercari
= link_to new_item_path, class: "footer-exhibition-button", data:{turbolinks: :false} do
  %div 出品
  %i.footer-exhibition-button__icon-camera
    = fa_icon 'camera'

app/views/items/_header.html.haml
%header.pc-header.visible-pc
  .pc-header-inner
    .pc-header-top
      .pc-header-top__logo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3236810361", size: "134x36", class: "pc-header-top__logo__image"
      
      = form_tag(search_items_path, method: :get, class: 'pc-header-search-form') do
        %input.pc-header-search-form__input{name: "keyword", placeholder: "何かお探しですか？", type: "text", value: ""}
        = button_tag (fa_icon "search"), type: 'submit', class: 'pc-header-search-form__input__icon'
        //= fa_icon "search", class: "pc-header-search-form__input__icon"
    
    .pc-header-nav-box.clearfix
      %nav.pc-header-nav-box__left#categories-list-parent
        %ul.pc-header-nav
          %li.pc-header-nav__list
            %h4
              = link_to "", class: "pc-header-nav__list__link" do
                = fa_icon "list-ul", text: "カテゴリーから探す", class: "pc-header-nav__list__link__icon"
           
            = render partial: 'items/categories', collection: @parents

          %li.pc-header-nav__list
            %h4
              = link_to "", class: "pc-header-nav__list__link.list-parent" do
                = fa_icon "tag", text: "ブランドから探す", class: "pc-header-nav__list__link__icon"
          
          

      - if user_signed_in?
        .pc-header-nav-box__right
          %ul.pc-header-user-nav
            %li.liked-items__link
              = link_to root_path, class: "pc-header-menu__link" do
                = fa_icon "heart", class: "pc-header-menu__link__icon"
                いいね！一覧
              
            %li{ data: {id: "pc-header-user-nav", key: "notification_list", url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}}
              = link_to search_ransack_items_path, data: { url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}, class: "pc-header-menu__link" do
                = fa_icon "bell", text: "お知らせ", class: "pc-header-menu__link__icon"
              
              %ul.pc-header-user-box.pc-header-notification-box.mypage__item-list{ data: { id: "pc-header-user-items"}}
            %li{ data: {id: "pc-header-user-nav", key: "todo_list", url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}}
              = link_to root_path, data: { url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}, class: "pc-header-menu__link" do
                = fa_icon "check", text: "やることリスト",class: "pc-header-menu__link__icon"
                
              %ul.pc-header-user-box.pc-header-todo-box.mypage__item-list{ data: { id: "pc-header-user-items"}}
            %li.pc-heade-user-box__mypage
              = link_to  user_path(current_user), class: "pc-header-menu__link" do
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", width: "32", alt: "", class: "pc-header-user__icon"
                %span マイページ
      - else
        .pc-header-nav-box__right
          %ul.pc-header-user-log-nav
            %li.pc-header-user-log-nav__sign-up
              = link_to signup_users_path, class: "pc-header-user-log-nav__sign-up__link" do
                新規会員登録
              
            %li.pc-header-user-log-nav__log-in
              = link_to new_user_session_path, class: "pc-header-user-log-nav__log-in__link" do
                ログイン

              -# %ul.pc-header-mypage__nav-list
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# いいね！一覧
                    -# %i.icon-arrow-right
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# 出品した商品 - 出品中
                    -# %i.icon-arrow-right
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# 出品した商品 - 取引中
                    -# %i.icon-arrow-right
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# 出品した商品 - 売却済み
                    -# %i.icon-arrow-right
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# 購入した商品 - 取引中
                    -# %i.icon-arrow-right
                -# %li
                  -# = link_to root_path, class: "pc-header-mypage__nav-list__item" do
                    -# 購入した商品 - 過去の取引
                    -# %i.icon-arrow-right

app/views/items/_main.html.haml
%main.toppage-main
  .main-header
  -# メイン上部の、キャンプの画像があるところ
  .main-content

    - if @items.present?
      %h3
        = link_to show_all_items_path do
          新着アイテム
      .main-content__list

        = render partial: "items/item", locals: {items: @items_limit_4, likes: @likes}

      .main-content__view-all
        = link_to show_all_items_path do
          すべての商品を見る

    - if @items_user.present?
      %h3
        = link_to show_user_all_items_path do
          = "#{current_user.nickname}さんの出品した商品"
      .main-content__list

        = render partial: "items/item", locals: {items: @items_user}

      .main-content__view-all
        = link_to show_user_all_items_path do
          すべての商品を見る

    - if @items_other.present?
      %h3
        = link_to show_other_all_items_path do
          他のユーザーの新着アイテム
      .main-content__list

        = render partial: "items/item", locals: {items: @items_other}

      .main-content__view-all
        = link_to show_other_all_items_path do
          すべての商品を見る

    -# TODO: カテゴリー・ブランド実装時に復活させて使う。
    -# %h2
    -#   ピックアップカテゴリー

  .main-footer
    .main-footer__left
      %h2
        スマホでかんたんフリマアプリ
      %p
        今すぐ無料ダウンロード！
      .main-footer__left__logo
        .main-footer__left__logo__mercari
          = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?2098311808", class: 'mercari', alt: "メルカリロゴ"
        .main-footer__left__logo__apple-google
          = link_to root_path do
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?2098311808", alt: "Appleロゴ"
          = link_to root_path do
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2098311808", alt: "Googleロゴ"
    .main-footer__right
      = image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?2098311808", alt: "メルカリ"

app/views/items/_user_item.html.haml
- user_items.each do |user_item|
  .main-content__list__container
    = link_to item_path(user_item.id) do
      .main-content__list__container__image
        = image_tag user_item.image.url, size: "213x213"
      .main-content__list__container__detail
        %h3
          = user_item.name
        .main-content__list__container__detail__info
          .main-content__list__container__detail__info__price
            = converting_to_jpy(user_item.price)
          .main-content__list__container__detail__info__like
            = fa_icon "heart", text: "1"
          - case user_item.trading.status
          - when '出品中'
            .main-content__list__container__detail__info__trading_status
              = "#{user_item.trading.status}"
          - when '取引中'
            .main-content__list__container__detail__info__trading_status.yellow
              = "#{user_item.trading.status}"
          - when '売却済'
            .main-content__list__container__detail__info__trading_status.blue
              = "#{user_item.trading.status}"
          - else
            .main-content__list__container__detail__info__trading_status.gray
              = "#{user_item.trading.status}"

app/views/items/index.html.haml
.default-container
  = render "header"
  = render "main"
  = render "footer"

app/views/items/payment_complete.html.haml
.payment_complete
  .payment_complete__mercari-logo
    = link_to root_path do
      = image_tag 'mercari_logo.png', alt: 'メルカリ'
  .payment_complete__top-image
    = image_tag 'thanks.png', alt: 'Thanks!'
  %p.payment_complete__appreciate
    メルカリをご利用いただきましてありがとうございます！
    %br
    お支払いが完了しました。
  %p.payment_complete__middle
    = fa_icon 'star'
    またのご利用、心からお持ちしております
    = fa_icon 'star'
  %p.payment_complete__bottom
    トップページへ戻るには
    = link_to root_path do
      ここ
    をクリックしてください。
  .payment_complete__line
  .payment_complete__info
    %p.payment_complete__info__item-name
      今回購入した商品
    .payment_complete__info__item-detail
      .payment_complete__info__item-detail__image{style: "background-image: url(#{@item.image})"}
      %ul
        %li
          商品名：
          %span
            = @item.name
        %li
          価格：
          %span
            = number_to_currency(@item.price, unit: '¥', precision: 0)

app/views/items/purchase_confirmation.html.haml
.default-container
  .purchase-header
    %h1
      = link_to root_path do
        = image_tag 'mercari_logo.png', alt: 'mercari'
  .confirmation
    %h2
      購入内容の確認
    .confirmation__item-info
      .confirmation__item-info__item
        = image_tag @item.image.url, alt: (@item.name)
        .confirmation__item-info__item__title
          = @item.name
      = form_with url: pay_items_path, method: :post do |f|
        .confirmation__item-info__price
          = number_to_currency(@item.price, unit: "￥", precision: 0)
          %span
            送料込み
        .confirmation__item-info__point
          ポイントはありません
        .confirmation__item-info__total-amount
          .confirmation__item-info__total-amount__left
            支払い金額
          .confirmation__item-info__total-amount__right
            %span
              = number_to_currency(@item.price, unit: "￥", precision: 0)
        = f.hidden_field :amount, value: (@item.price)
        .payjp
          %script.payjp-button{"data-key": Rails.application.credentials[:payjp][:public_key], "data-partial": "false", "data-submit-text": "購入する", "data-text": "支払う", src: "https://checkout.pay.jp/", type: "text/javascript"}
    .confirmation__shipping-info
      %h3
        配送先
      - if @address.present?
        %address
          〒
          = @address.postalcode
          %br
          = @address.prefecture
          = @address.city
          = @address.number
          = @address.building if @address.building
          %br
          = current_user.last_name
          = current_user.first_name
        %p
          = link_to edit_user_address_path(current_user.id, current_user.address.id), data:{turbolinks: :false} do
            変更する
            = fa_icon 'chevron-right'
      - else
        %address
          住所が未登録です
        %p
          = link_to new_user_address_path(current_user.id), data:{turbolinks: :false} do
            登録する
            = fa_icon 'chevron-right'

  = render 'devise/shared/gray_footer'

app/views/items/search.html.haml
= render 'header'

.breadcrumb
  - breadcrumb :item_search
  = breadcrumbs separator: " &rsaquo; "
  
.search
  .search__detail-search
    = link_to search_ransack_items_path do
      詳細検索モードへ
  .search__result
    %h2
      - if @typed_keyword.present? then
        = @typed_keyword
        %span
          の検索結果
      - else
        新着商品
    .search__result__item-amount
      = @amount
      件表示
    .search__result__item-list
      - @search.each do |item|
        .search__result__item-list__container
          = link_to item_path(item.id) do
            .search__result__item-list__container__image
              %span{style: "background-image: url(#{item.image})"}
            .search__result__item-list__container__detail
              %h3
                = item.name
              .search__result__item-list__container__detail__info
                .search__result__item-list__container__detail__info__price
                  = number_to_currency(item.price, unit: "￥", precision: 0)
                .search__result__item-list__container__detail__info__like
                  = fa_icon "heart", text: "1"

= render 'footer'

app/views/items/search_ransack.html.haml
.default-container.clearfix
  = render "header"

  .breadcrumb
    - breadcrumb :search_ransack
    = breadcrumbs separator: " &rsaquo; "

  %main.search_ransack.clearfix
    .search_box
      .search_box__condition
        %h3.bold 詳細検索
        = search_form_for(@q, url:search_ransack_items_path, class: 'ransack_form') do |f|
          .ransack_form__item
            = f.label :name_or_description_cont, 'キーワードを追加する'
            = f.search_field :name_or_description_cont, placeholder: '複数ワードは未実装'
          .ransack_form__item
            = f.label :price, '価格の範囲'
            = f.search_field :price_gteq, class: 'ransack_form__item__price', placeholder: '¥ min'
            %span 円以上
            = f.search_field :price_lteq, class: 'ransack_form__item__price', placeholder: '¥ MAX'
            %span 円以下
          .ransack_form__item
            = f.label :item_status_eq, '商品の状態'
            = f.select :item_status_eq ,Item.item_statuses.map{|k, v| [Item.item_statuses_i18n[k], v]}, include_blank: '指定なし'
          .ransack_form__item
            = f.label :trading_status_eq, '出品ステータス'
            = f.select :trading_status_eq ,Trading.statuses.map{|k, v| [Trading.statuses_i18n[k], v]}, include_blank: '指定なし'
          .ransack_form__button
            = f.submit '検索', class: 'ransack_form__button__submit'

    .main-content.clearfix
      %h2.clearfix
        商品の詳細検索をする
      %h3.clearfix
      - if @items.present?
        .main-content__list.clearfix
          = render partial: "items/user_item", locals: {user_items: @items}

  .view-all.clearfix
    = link_to root_path do
      トップページに戻る

  = render "footer"

app/views/items/show_other_all.html.haml
.default-container
  = render "header"

  %main.show_user_all.clearfix
    .main-content.clearfix
      %h2
        他のユーザーの全ての商品をみる
      %h3
      - if @items.present?
        .main-content__list.clearfix
          = render partial: "items/user_item", locals: {user_items: @items}

    .main-content__view-all
      = link_to root_path do
        トップページに戻る

  = render "footer"

app/views/items/show_user_all.html.haml
.default-container
  = render "header"

  %main.show_user_all.clearfix
    .main-content.clearfix
      %h2
        = "#{current_user.nickname} さんの全ての商品を見る"
      %h3
      - if @items.present?
        .main-content__list.clearfix
          = render partial: "items/user_item", locals: {user_items: @items}

    .main-content__view-all
      = link_to root_path do
        トップページに戻る

  = render "footer"