config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'
  
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }

  # devise_scope :user do
  #   get "sign_in", to: "users/sessions#new"
  #   get "sign_out", to: "users/sessions#destroy" 
  # end

  resources :users, :only => [:show, :edit] do
    resources :cards, only: [:new, :create, :index]
    resources :addresses, only: [:new, :create, :show, :edit, :update]

    member do
      get 'mypage_identification'
      get 'telephone_authentication'
    end
    
    collection do
      get 'signup_complete'
      get 'signup'
      get 'logout'
    end
  end


  resources :items do
    resources :likes, only: [:create, :destroy]

    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
      get 'show_all'
      get 'show_user_all'
      get 'show_other_all'
      get 'search'
      get 'search_ransack'
    end

    member do
      get 'purchase_confirmation'
      get 'payment_complete'
      patch 'switch_status'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
  end

  def index
  end

end

app/views/cards/index.html.haml
.default-container
  
  =render partial: 'items/header'

  .breadcrumb
    - breadcrumb :card_index
    = breadcrumbs separator: " &rsaquo; "

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .card_show_right-content
      %h2.cs_head 支払い方法

      .cs_group

        .cs_group__title
          %h3.bold クレジットカード一覧

        .cs_group__list
          = image_tag "logo_visa.gif", class: 'cs_group__list__image', size: '49x32', alt: ""
          .cs_group__list__pay_num ************1234
          .cs_group__list__pay_num 08 / 19
          = form_with url: 'https://www.mercari.com/jp/mypage/card/delete/', method: :post, local: true, id: 'charge-form', class: 'cs_form' do |f|
            =f.text_field :card_id, type: "hidden", name: "card_id", value: "", class: 'cs_form__card_id'
            = f.submit '削除する',class: 'cs_form__submit_btn'

        .cs_group__info
          %p.text-right
            = link_to root_path, class: 'cs_group__info__link', target: "_blank", data:{turbolinks: :false} do
              支払い方法について
              = fa_icon 'angle-right', class: 'icon-angle-right bold'
      
  =render partial: 'items/footer'


  / %label 登録クレジットカード情報
  /   %br
  /   = "**** **** **** " + @default_card_information.last4
  /   %br
  /     exp_month = @default_card_information.exp_month.to_s
  /     exp_year = @default_card_information.exp_year.to_s.slice(2,3)
  /     exp_month + " / " + exp_year
  /   = form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
  /     %input{ type: "hidden", name: "card_id", value: "" }
  /     %button 削除する

app/views/cards/new.html.haml
.default-container

  .header_card_new
    %h1.header_card_new--wrap
      = link_to root_path, class: 'header_only-logo--wrap__link', data:{turbolinks: :false} do
        = image_tag "mercari_logo.png", class: 'header_only-logo--wrap__link__image', size: '185x52', alt: "mercari"
    .header_card_new__stage
      %ol.header_card_new__stage__list.clearfix
        %li
          %span 会員情報
          .stage-status.active 
        %li
          %span 電話番号認証
          .stage-status.active 
        %li
          %span お届け先住所入力
          .stage-status.active 
        %li.active 
          %span 支払い方法
          .stage-status.active 
        %li
          %span 完了
          .stage-status

  %main.card_new_container
    %h2.card_new_head 支払い方法

    = form_with url: 'users_path', local: true, class: 'card_new_form' do |f|

      .card_new_form__group
        %label.bold{ for: "payment_card_id" } カード番号
        %label.card_new_form__group--arbitrary 必須
        = f.text_field :payment_card_id, name: "payment_card_id", class: 'card_new_form__group__input', placeholder: "半角数字のみ"
        %ul.card_new_form__group__card_list
          %li
            = image_tag "logo_visa.gif", class: 'card_new_form__group__card_list__image', size: '31x20', alt: ""
          %li
            = image_tag "logo_mastercard.gif", class: 'card_new_form__group__card_list__image', size: '31x20', alt: ""
          %li
            = image_tag "logo_saisoncard.gif", class: 'card_new_form__group__card_list__image', size: '30x20', alt: ""
          %li
            = image_tag "logo_jcb.gif", class: 'card_new_form__group__card_list__image', size: '27x20', alt: ""
          %li
            = image_tag "logo_amex.gif", class: 'card_new_form__group__card_list__image', size: '24x20', alt: ""
          %li
            = image_tag "logo_diners.gif", class: 'card_new_form__group__card_list__image', size: '27x20', alt: ""
          %li
            = image_tag "logo_discover.gif", class: 'card_new_form__group__card_list__image', size: '30x20', alt: ""

      .card_new_form__group.card_new_form__expire
        %label.bold{ for: "expire_mm" } 有効期限
        %label.card_new_form__group--arbitrary 必須
        %br
        .card_new_form__group--select-wrap-half
          = fa_icon 'angle-down 2x', class: 'icon-angle-down bold'
          = f.select :expire_mm, [['01'], ['02'], ['03'], ['04'], ['05'], ['06'], ['07'], ['08'], ['09'], ['10'], ['11'], ['12']]
          %span 月
        .card_new_form__group--select-wrap-half
          = fa_icon 'angle-down 2x', class: 'icon-angle-down bold'
          = f.select :expire_yy, [['19'], ['20'], ['21'], ['22'], ['23'], ['24'], ['25'], ['26'], ['27'], ['28']]
          %span 年

      .card_new_form__group
        %label.bold{ for: "security_code" } セキュリティコード
        %label.card_new_form__group--arbitrary 必須
        = f.text_field :security_code, name: "security_code", class: 'card_new_form__group__input', placeholder: "カード背面４桁もしくは３桁の番号"
        %p.text-right
          %span.card_new_form__group__question ？
          %span カード裏面の番号とは？

      /= f.submit '次へ進む',class: 'card_new_form__submit_btn'
      = link_to '次へ進む', signup_complete_users_path, class: 'card_new_form__submit_btn', data:{turbolinks: :false}

  =render partial: 'devise/shared/gray_footer'

app/views/cards/show.html.haml
.default-container
  
  =render partial: 'items/header'

  %main.mypage_container.clearfix

    =render partial: 'users/left-content'

    .card_show_right-content
      %h2.cs_head 支払い方法

      .cs_group

        .cs_group__title
          %h3.bold クレジットカード一覧

        .cs_group__list
          = image_tag "logo_visa.gif", class: 'cs_group__list__image', size: '49x32', alt: ""
          .cs_group__list__pay_num ************1234
          .cs_group__list__pay_num 08 / 19
          = form_with url: 'https://www.mercari.com/jp/mypage/card/delete/', method: :post, local: true, id: 'charge-form', class: 'cs_form' do |f|
            =f.text_field :card_id, type: "hidden", name: "card_id", value: "", class: 'cs_form__card_id'
            = f.submit '削除する',class: 'cs_form__submit_btn'

        .cs_group__info
          %p.text-right
            = link_to "https://www.mercari.com/jp/help_center/category/6/", class: 'cs_group__info__link', target: "_blank", data:{turbolinks: :false} do
              支払い方法について
              = fa_icon 'angle-right', class: 'icon-angle-right bold'
      
  =render partial: 'items/footer'


  / %label 登録クレジットカード情報
    / %br
    / = "**** **** **** " + @default_card_information.last4
    / %br
    /   exp_month = @default_card_information.exp_month.to_s
    /   exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    /   exp_month + " / " + exp_year
    / = form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
    /   %input{ type: "hidden", name: "card_id", value: "" }
    /   %button 削除する